on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v4
      #- name: Build the Docker image
        #run: |
          #cd umami
          #docker build . --file Dockerfile --tag kadonne55/cloud_computing:latest
      #- name: Push image to Docker hub
        #run: |
          #docker login -u kadonne55 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          #docker push kadonne55/cloud_computing:latest
      - name: Configure AWS credentials action for github actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.2
      - name: Build Terraform
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: terraform
